trigger:
- organicfrontend

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 👇 MOVE INTO FRONTEND FOLDER
- script: |
    cd organicfrontend
    npm install
  displayName: 'Install dependencies'

- script: |
    cd organicfrontend
    npm run build
  displayName: 'Build React app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'frontend/build'
    artifactName: 'react-build'
  displayName: 'Publish build artifacts'