trigger:
- organicfrontend

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    echo "FILES:"
    ls -R
  displayName: 'Debug files'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd OrganicShopFinalProject
    npm install
  displayName: 'Install dependencies'

- script: |
    cd OrganicShopFinalProject
    npm run build
  displayName: 'Build React app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'OrganicShopFinalProject/build'
    artifactName: 'react-build'
  displayName: 'Publish build artifacts'