// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganicShopBackend.Data;

#nullable disable

namespace OrganicShopBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250214063442_updateimages")]
    partial class updateimages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrganicShopBackend.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UniqueOrderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Admin Street",
                            Email = "saiakash200236@gmail.com",
                            Name = "Freshio",
                            PasswordHash = "$2a$11$XjfGUaeIu.udshg8gpc/teGGci1JP9cuYTkqKQF48NZfvGbYs8wpm",
                            PhoneNumber = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Delivery Street",
                            Email = "osdeliveryteam@gmail.com",
                            Name = "Organic Delivery",
                            PasswordHash = "$2a$11$DwwJYywXEdN8.QT2WBrv8OH4clJLlZXPEYUlTwUan3YutA6ocfE6y",
                            PhoneNumber = "9876543210",
                            Role = "DeliveryTeam"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Images")
                        .HasColumnType("longtext");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.",
                            DiscountPercentage = 4.05m,
                            Images = "[\"/images/products/potato.jpg\"]",
                            MinimumOrderQuantity = 29,
                            Price = 45m,
                            QuantityInStock = 8,
                            Rating = 3.8199999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "W4NOBW45",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Potatoes/thumbnail.png",
                            Title = "Potatoes",
                            WarrantyInformation = "5 year warranty",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 2,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
                            DiscountPercentage = 17.89m,
                            Images = "[\"/images/products/redonion.png\"]",
                            MinimumOrderQuantity = 40,
                            Price = 50m,
                            QuantityInStock = 86,
                            Rating = 4.0800000000000001,
                            ReturnPolicy = "60 days return policy",
                            ShippingInformation = "Ships in 2 weeks",
                            Sku = "TAF870KJ",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/thumbnail.png",
                            Title = "Red Onions",
                            WarrantyInformation = "Lifetime warranty",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 3,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
                            DiscountPercentage = 11.44m,
                            Images = "[\"/images/products/cucumber.png\"]",
                            MinimumOrderQuantity = 7,
                            Price = 30m,
                            QuantityInStock = 22,
                            Rating = 4.71,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships overnight",
                            Sku = "6KGF2K6Z",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
                            Title = "Cucumber",
                            WarrantyInformation = "5 year warranty",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 4,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh broccoli, packed with vitamins, perfect for healthy meals and salads.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"/images/products/beetroot.png\"]",
                            MinimumOrderQuantity = 5,
                            Price = 60m,
                            QuantityInStock = 20,
                            Rating = 4.5,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0Y4NORN2",
                            Tags = "[\"greens\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Broccoli/thumbnail.png",
                            Title = "Beetroot",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 5,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh and juicy tomatoes, perfect for salads, sauces, and cooking.",
                            DiscountPercentage = 15.0m,
                            Images = "[\"/images/products/tomato.png\"]",
                            MinimumOrderQuantity = 10,
                            Price = 90m,
                            QuantityInStock = 50,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0T3M0T0",
                            Tags = "[\"fresh\",\"vegetables\",\"rich in vitamins\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Tomato/thumbnail.png",
                            Title = "Tomato",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 6,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Crunchy and sweet carrots, rich in beta-carotene, ideal for snacks and cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"/images/products/carrot.jpg\"]",
                            MinimumOrderQuantity = 5,
                            Price = 50m,
                            QuantityInStock = 40,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0C4R0T0",
                            Tags = "[\"snack\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Carrot/thumbnail.png",
                            Title = "Carrot",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 7,
                            AvailabilityStatus = "In Stock",
                            Category = "essentials",
                            Description = "Fresh and nutritious milk, a staple for various recipes and daily consumption.",
                            DiscountPercentage = 15.09m,
                            Images = "[\"/images/products/milk.jpg\"]",
                            MinimumOrderQuantity = 41,
                            Price = 35m,
                            QuantityInStock = 57,
                            Rating = 3.1400000000000001,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "VOZKMF40",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png",
                            Title = "Milk",
                            WarrantyInformation = "6 months warranty",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 8,
                            AvailabilityStatus = "In Stock",
                            Category = "essentials",
                            Description = "Pure and clarified butter, perfect for cooking and traditional dishes.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"/images/products/cookingoil.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 400m,
                            QuantityInStock = 40,
                            Rating = 4.7000000000000002,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "GH3E5E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Ghee/thumbnail.png",
                            Title = "Cooking Oil",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 9,
                            AvailabilityStatus = "In Stock",
                            Category = "essentials",
                            Description = "Rich and creamy butter, perfect for spreading or cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"/images/products/rice.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 270m,
                            QuantityInStock = 25,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "BU8T7E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Butter/thumbnail.png",
                            Title = "Rice",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 10,
                            AvailabilityStatus = "In Stock",
                            Category = "essentials",
                            Description = "Delicious and creamy cheese, perfect for sandwiches and pizzas.",
                            DiscountPercentage = 7.5m,
                            Images = "[\"/images/products/water.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 300m,
                            QuantityInStock = 20,
                            Rating = 4.9000000000000004,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "CH4E3S",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cheese/thumbnail.png",
                            Title = "Water",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 11,
                            AvailabilityStatus = "In Stock",
                            Category = "essentials",
                            Description = "Creamy and tangy yogurt, a great addition to smoothies and desserts.",
                            DiscountPercentage = 10.0m,
                            Images = "[\"/images/products/proteinpowder.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 75m,
                            QuantityInStock = 60,
                            Rating = 4.2999999999999998,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "YO3G5T",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Yogurt/thumbnail.png",
                            Title = "Protein Powder",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 12,
                            AvailabilityStatus = "In Stock",
                            Category = "eggandmeat",
                            Description = "Fresh and tender chicken meat, suitable for various culinary preparations.",
                            DiscountPercentage = 10.46m,
                            Images = "[\"/images/products/chicken.png\"]",
                            MinimumOrderQuantity = 46,
                            Price = 110m,
                            QuantityInStock = 69,
                            Rating = 4.6100000000000003,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "G5YEHW7B",
                            Tags = "[\"Non-veg\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png",
                            Title = "Chicken Meat",
                            WarrantyInformation = "Lifetime warranty",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 13,
                            AvailabilityStatus = "In Stock",
                            Category = "eggandmeat",
                            Description = "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
                            DiscountPercentage = 5.8m,
                            Images = "[\"/images/products/egg.jpg\"]",
                            MinimumOrderQuantity = 43,
                            Price = 6m,
                            QuantityInStock = 10,
                            Rating = 4.46,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships overnight",
                            Sku = "YA617RI7",
                            Tags = "[\"Non-veg\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png",
                            Title = "Eggs",
                            WarrantyInformation = "3 year warranty",
                            Weight = 4.0
                        },
                        new
                        {
                            ProductId = 14,
                            AvailabilityStatus = "In Stock",
                            Category = "eggandmeat",
                            Description = "Quality fish steak, suitable for grilling, baking, or pan-searing.",
                            DiscountPercentage = 7m,
                            Images = "[\"/images/products/fish.png\"]",
                            MinimumOrderQuantity = 49,
                            Price = 70m,
                            QuantityInStock = 99,
                            Rating = 4.8300000000000001,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "XNIH1MTA",
                            Tags = "[\"Non-veg\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png",
                            Title = "Fish Steak",
                            WarrantyInformation = "1 year warranty",
                            Weight = 8.0
                        },
                        new
                        {
                            ProductId = 15,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
                            DiscountPercentage = 15.5m,
                            Images = "[\"/images/products/greenbell.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 20m,
                            QuantityInStock = 89,
                            Rating = 4.2800000000000002,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships overnight",
                            Sku = "HU7S7VQ0",
                            Tags = "[\"Vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png",
                            Title = "Green Bell Pepper",
                            WarrantyInformation = "5 year warranty",
                            Weight = 50.0
                        },
                        new
                        {
                            ProductId = 16,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
                            DiscountPercentage = 18.51m,
                            Images = "[\"/images/products/greenchilli.png\"]",
                            MinimumOrderQuantity = 43,
                            Price = 30m,
                            QuantityInStock = 8,
                            Rating = 4.4299999999999997,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "Y4RM3JCB",
                            Tags = "[\"Vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png",
                            Title = "Green Chili Pepper",
                            WarrantyInformation = "No warranty",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 17,
                            AvailabilityStatus = "Low Stock",
                            Category = "fruits",
                            Description = "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
                            DiscountPercentage = 10.32m,
                            Images = "[\"/images/products/kiwi.png\"]",
                            MinimumOrderQuantity = 8,
                            Price = 100m,
                            QuantityInStock = 10,
                            Rating = 4.3700000000000001,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 3-5 business days",
                            Sku = "0X3NORB9",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png",
                            Title = "Kiwi",
                            WarrantyInformation = "6 months warranty",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 18,
                            AvailabilityStatus = "Out of Stock",
                            Category = "fruits",
                            Description = "Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.",
                            DiscountPercentage = 17.81m,
                            Images = "[\"/images/products/lemon.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 10m,
                            QuantityInStock = 0,
                            Rating = 4.25,
                            ReturnPolicy = "90 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "J074TE3H",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Lemon/thumbnail.png",
                            Title = "Lemon",
                            WarrantyInformation = "3 year warranty",
                            Weight = 20.0
                        },
                        new
                        {
                            ProductId = 19,
                            AvailabilityStatus = "In Stock",
                            Category = "fruits",
                            Description = "Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.",
                            DiscountPercentage = 16.35m,
                            Images = "[\"/images/products/mulberry.png\"]",
                            MinimumOrderQuantity = 50,
                            Price = 75m,
                            QuantityInStock = 79,
                            Rating = 3.1899999999999999,
                            ReturnPolicy = "60 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "0M1K7RRC",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Mulberry/thumbnail.png",
                            Title = "Mulberry",
                            WarrantyInformation = "3 months warranty",
                            Weight = 50.0
                        },
                        new
                        {
                            ProductId = 20,
                            AvailabilityStatus = "In Stock",
                            Category = "fruits",
                            Description = "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.",
                            DiscountPercentage = 19.59m,
                            Images = "[\"/images/products/strawberry.jpg\"]",
                            MinimumOrderQuantity = 38,
                            Price = 150m,
                            QuantityInStock = 9,
                            Rating = 4.5,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "LPP7I4JZ",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Strawberry/thumbnail.png",
                            Title = "Strawberry",
                            WarrantyInformation = "1 year warranty",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 21,
                            AvailabilityStatus = "In Stock",
                            Category = "fruits",
                            Description = "Crisp and juicy apples, perfect for snacking or adding to salads.",
                            DiscountPercentage = 10.0m,
                            Images = "[\"/images/products/apple.jpg\"]",
                            MinimumOrderQuantity = 1,
                            Price = 200m,
                            QuantityInStock = 50,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1-3 business days",
                            Sku = "AP5L8E23",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png",
                            Title = "Apple",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 22,
                            AvailabilityStatus = "In Stock",
                            Category = "fruits",
                            Description = "Fresh and ripe bananas, rich in potassium, perfect for snacking or smoothies.",
                            DiscountPercentage = 10.0m,
                            Images = "[\"/images/products/banana.jpg\"]",
                            MinimumOrderQuantity = 1,
                            Price = 25m,
                            QuantityInStock = 100,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1-3 business days",
                            Sku = "BA7A9M23",
                            Tags = "[\"Fruits\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Banana/thumbnail.png",
                            Title = "Banana",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 30.0
                        });
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Cart", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganicShopBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.HasOne("OrganicShopBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.OrderItem", b =>
                {
                    b.HasOne("OrganicShopBackend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
